name: Rust

on:
  push:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/rust.yml'
  pull_request:
    paths:
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/rust.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: cargo check
        run: cargo check --all-targets
      - name: cargo test
        run: cargo test --all-targets
